- karma.conf.js
- src/hls-adapter.js
- test/src/hls-adapter.spec.js
consider hls configuration for live edge - `liveSyncDuration` and `liveSyncDurationCount`
> chore: consider hls configuration for live edge calculation

- package.json
- yarn.lock
upgrade hls.js version to 0.8.1
> chore: upgrade hls.js version to 0.8.1

- package.json
- test/src/hls-adapter.spec.js
- yarn.lock
> fix(FEC-7032): update hls.js version

- package.json
- yarn.lock
> fix(FEC-7313) - [Universal live HLS] the stream is flashing

- .eslintrc.json
- karma.conf.js
- src/hls-adapter.js
- webpack.config.js
add export of name and version of library.
> feat: export name and version on module

- src/hls-adapter.js
add HLS buffer stalled error code
> fix: add error code for buffer stalled

- src/default-config.json
- src/hls-adapter.js
Add default-config.json for component.
> feat: add default-config json container

- src/errors.js
- src/hls-adapter.js
* Move error name to error details to a map
* add types
* some cleanup
> chore: clean up error handling

- test/src/json/hls_sources.json
> fix: build

- src/hls-adapter.js
> chore: add log when cannot calculate the live edge

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
> chore: use EventType to get the playkit events

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
- test/src/json/hls_sources.json
Fix build.
Skip unnecessary test until we have better way to test it.
> chore: fix build

- src/hls-adapter.js
- src/jsonp-ploader.js
Handle rejection from the JSONP util and pass a timeout value.
> fix(FEC-8026): external OTT VOD/Live media doesn't works on IE 11

- src/hls-adapter.js
set start position only if configure start time is bigger then -1.
> fix(FEC-8203): Live with DVR is not playing live edge in first play

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
- test/src/json/player_tracks.json
If the media recovered successfully, trigger media recovered event
> fix(FEC-8233): handle media & error recovering

- README.md
> chore: fix hls.js documentation url

- package.json
- yarn.lock
> fix(FEC-7887, FEC-7953, SUP-14111): upgrade hlsjs to 0.10.1

- .flowconfig
- flow-typed/modules/playkit-js.js
- package.json
- src/errors.js
- src/hls-adapter.js
- src/index.js
- src/jsonp-ploader.js
- test/src/hls-adapter.spec.js
- test/utils/test-utils.js
- webpack.config.js
configuring and changing to the new build process
> chore: new build

- src/hls-adapter.js
Adding getCurrentQuality API for the quality watcher feature.
https://github.com/kaltura/playkit-js/pull/295
> feat(FEC-7808): quality watcher for the player

- package.json
- yarn.lock
> feat(FEC-8507): update to hlsjs 12.1

- package.json
- yarn.lock
> fix(FEC-8780): captions not shown after seek

- src/hls-adapter.js
Listening to FRAG_LOAD and MANIFEST_LOAD and raising the events to the engine
> FEC-8975 QoS data enhancement

- src/hls-adapter.js
feat(FEC-8975): adding frag url to the frag loaded event
> feat(FEC-8975): adding frag url to the frag loaded event

- package.json
- src/hls-adapter.js
- test/src/hls-adapter.spec.js
- test/src/json/hls_sources.json
- yarn.lock
Destroy and initialize hls.js before and after ads for now(should be resolved by hls.js later and it'll be replace by attach detach media)
> feat(FEC-9227): support reInit of MSE

- src/hls-adapter.js
add check for MSE adapter to make sure we'll select the correct adapter for devices
> fix(FEC-9342): Disable shaka on iOS

- package.json
- yarn.lock
> chore: update playkit-js version

- src/hls-adapter.js
> fix(FEC-9512): save hlsjs lib on mediaSource adapter

- src/hls-adapter.js
- src/loader.js
- test/src/hls-adapter.spec.js
Support `requestFilter` returning promise
> feat(FEC-9452): async request filter handlers

- package.json
- yarn.lock
hls.js added multiple improvements and bug fixes for live and VOD.
> feat(FEC-10296): upgrade hls.js to 0.14.9

- .babelrc
change modules value back to default.
> build: change modules to default value

- test/src/hls-adapter.spec.js
Issue: targetBuffer could be a float number so it won't be an exactly equal number.
tests failed with stream that is not valid on Travis.
Solution: check the diff between and round it will ignore these small changes.
Set Big bunny stream for testing.
> test: targetBuffer check doesn't perfectly equal and replace invalid stream

- src/hls-adapter.js
return promise which will be resolved or rejected at the end of reset.
> fix(FEC-10662): incorrect flow in destroy process

- src/hls-adapter.js
Issue: it's an internal inconsistency when we add handlers on addBinding and didn't remove it or removing incorrectly on removeBinding.
On change media it doesn't cause an issue since destroy called.
Solution: remove the handler on removeBinding
> fix: events doesn't remove in removeBinding method

- package.json
- test/src/hls-adapter.spec.js
- yarn.lock
Related to https://github.com/kaltura/kaltura-player-js/pull/414
resolves FEC-11013
> feat(FEC-11013): upgrade to hlsjs latest (0.14.17)

- package.json
- src/hls-adapter.js
- test/src/json/player_tracks.json
- yarn.lock
add an API applyABRRestriction to apply ABR restrictions and show only available tracks after restriction.
> feat(FEC-10980): Enable setting ABR settings on-the-fly

- package.json
- src/hls-adapter.js
- yarn.lock
> feat(FEC-11337): Upgrade hls.js to 1.0 

- src/hls-adapter.js
> feat(FEC-10817): expose the current time of the video element in live streams

- test/src/hls-adapter.spec.js
Issue: sources don't pass throw constructor, it changed to setSources API
> tests: API change in playkit-js

- src/hls-adapter.js
If we have a live stream with CEA 608 captions, and we seek from Live Edge to point A to point C to point B,
where [Time A] < [Time B] < [Time C] < [Live Edge], 
a bug in hls.js causes the cue created at **point C** to have the start time of **point A**, and the text of cue C to be visible at the wrong position. 
As a workaround, if after seek we detect a cue in the cues list which has an endTime greater than its next sibling - we remove that cue.
Fixes FEC-11760.
> fix(FEC-11760): Live captioning with Virtuvent not updating captions

- .flowconfig
- karma.conf.js
- package.json
- src/hls-adapter.js
- test/src/hls-adapter.spec.js
- yarn.lock
Fire `TIMED_METADATA_ADDED` once a new id3 cue has been added 
Solves FEC-11761
Depends on https://github.com/kaltura/playkit-js/pull/623
> feat(FEC-11761): expose stream timed metadata - phase 2

- package.json
- test/src/json/hls_sources.json
- yarn.lock
> fix(FEC-12780): upgrade hls.js v1.2.8

- src/hls-adapter.js
solves: FEC-12760
related pr: https://github.com/kaltura/playkit-js/pull/682
> fix(FEC-12760): Blank Transcript Box In V7 Player

- package.json
- yarn.lock
Upgrade hls.js v1.3.1
FEC-12873
> feat(FEC-12873): upgrade hls.js library to v1.3.1

- src/hls-adapter.js
FEC-12848 log capLevelOnFPSDrop state
> fix(FEC-12848) add log for capLevelOnFPSDrop state

- package.json
- yarn.lock
> feat(FEC-13083): upgrade hls.js 1.3.5

- src/hls-adapter.js
Reverts kaltura/playkit-js-hls#209
> Revert "fix(SUP-39117): handle when audio tracks are returned with video tracks"

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- webpack.config.js
- yarn.lock
> fix(FEC-13669): Aligning all repos with the latest kaltura-browserslist-config to eliminate different browser target among repos

- src/hls-adapter.ts
Add error logs when media absent in manifest
> fix(SUP-45743): Add error log on missed media in manifest

- package.json
- src/hls-adapter.ts
- yarn.lock
upgrade hls version
[SUP-49180]: https://kaltura.atlassian.net/browse/SUP-49180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-49180): [Vanguard] VOD entries distorted
