kaltura/playkit-js-hls

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
align with playkit-js caption refactor
need to hide native text tracks and use emulated display via HTML because not all browsers support all TextTrack API or VTTCue as defined by spec
> feat: caption refactor

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
- test/src/json/hls_tracks.json
- test/src/json/player_tracks.json
use hlsjs api to get the subtitles, instead of video element api, which remains the tracks from previous playback.
> fix(fec-7323): captions remains from previous video

- src/default-config.json
- src/hls-adapter.js
added maxMexBufferLength = 60 (60 seconds) to the default configuration 
(i didn't pick the configuration name)
> fix(FEC-7741): added max buffer length to default configuration

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
Send the hls `this` levels instead of the event data levels (the `this._hls.levels` are the filtered levels from the ManifestParsed event (MANIFEST_PARSED sent before MANIFEST_LOADED).
> fix(FEC-7873): player shows audio and video flavour and in case of choosing audio flavour player stuck

- src/hls-adapter.js
Handling a situation after audio track is changed, only in IE and Edge.
If a waiting event is sent, we send playing event.
@dan-ziv, I didn't use the event manager i thought it's an overkill, cause it's not imported anyway.. let me know if you think otherwise.
> fix(FEC-7896): endless spinner appears right after changing audio track in IE and Edge

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
live edge calculation refactor:
* use `hls.liveSyncPosition` if available
* use the `hls.currentLevel` property to get data of the current level instead of getting the index 0 level Arbitrarily.
* if any calculation is unavailable return the duration
> fix(FEC-7913): Live - player doesn't seek to live edge on resume

- src/hls-adapter.js
Resolving the load promise only on `metadataloaded` html5 event, 
not on `LEVEL_UPDATED` hls event which is too early for text track selection.
> fix(FEC-7623): preset captions are no displayed

- src/hls-adapter.js
since we resolve the ready promise with `loadedmetadata` event listener [here](https://github.com/kaltura/playkit-js-hls/pull/50) 
we have to remove this listener once the metadata is loaded or on destroy for change media flow
> fix: remove loadedmetadata listener once metadata loaded

- src/hls-adapter.js
Move the src getter to the base adapter since they all have the same implementation now.
> fix(FEC-8079): move src getter to base adapter 

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
Add error handling for html5 video media error `MEDIA_ERR_DECODE`
> feat(FEC-8209): handle MEDIA_ERR_DECODE errors

- src/hls-adapter.js
The merge order for the config gave default config precedence over the application supplied config
> fix(FEC-8396): media source adapters default config overrides the player supplied config

- src/hls-adapter.js
parse 608/708 tracks by the video element `textTrack` api
depends on 
https://github.com/kaltura/playkit-js/pull/265
https://github.com/kaltura/playkit-js-ui/pull/254
> feat(FEC-8390, FEC-8246): support 608/708 captions

- src/hls-adapter.js
hls.js has an issue with selecting audio track before the manifest was loaded(it was solved in 0.11.0 which we haven't upgraded yet to).
To overcome the issue we added a workaround in #69  but it causes an issue, that was also fixed in 0.11.0 :-( for incorrect indexes of audio tracks when using different audio group ids.
So - this is another "fast" workaround until we upgrade to hls.js 0.11.0
> fix(FEC-8506): fail to resolve manifest load with multi-audio streams

- src/hls-adapter.js
When we select initial captions then hls.js has an internal bug that fails.
This is a workaround until issue is fixed.
see detailed issue explainer here: https://github.com/video-dev/hls.js/issues/1948
> fix(FEC-8557): workaround for hls.js text track selection issues

- src/hls-adapter.js
resolve the promise in timeout as a workaround for [hlsls issue ](https://github.com/video-dev/hls.js/issues/1948).
> fix(FEC-8690): player stuck with endless spinner on change media

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- src/hls-adapter.js
- yarn.lock
Listening to hlsjs `MEDIA_ATTACHED` event before selecting a text track. 
Created a promise that will be resolved when this event is triggered.
Only on `promise.resolve()` we will select a text track.
> fix(FEC-8764): after change media / refresh the video has no subtitles

- src/hls-adapter.js
- test/src/json/hls_sources.json
Fire `hlsFragParsingMetadata` events for live tracking
> feat(FEC-8044): ima-dai plugin

- src/hls-adapter.js
Add support for replay after ads finish to return to beginning
> fix(FEC-9262): playback doesn't return to start after playback with ads in LG TV

- package.json
- src/hls-adapter.js
- src/jsonp-ploader.js
- src/loader.js
- yarn.lock
* Implement a new `loader` which passes the context to `xhrSetup` function 
* Handle `condig.network.requestFilter` by hls [xhrsetup](https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup) config
depends on https://github.com/kaltura/playkit-js/pull/391
> feat(FEC-9271): expose interface and methods to enable customizing DRM request/response

- src/hls-adapter.js
occurred on DRM content only `LOAD_DATA` on SMART TV could take a moment and user can seek before - check if `SEEKED` event occurred before.
Couldn't resolve with `LOADED_METADATA` seek failed on earlier version of TV.
> fix(FEC-9316): seek doesn't work before video finished loading

- src/hls-adapter.js
Solve FEC-9316.
unlisten of loaded_data wasn't always earlier enough.
add check for seeked event occurred and don't seek on loaded_data event
> fix: seek doesn't work before video finished loading

- src/hls-adapter.js
- test/src/hls-adapter.spec.js
in onError, added error object assignment to be fired also in manifest reload
> fix(FEC-9735): when there is reload attempt on a Network error, no error object is set in the payload

- src/hls-adapter.js
**Issue:** Select text by lang or label is not reliable because they could be the same for more than one track
(e.g. when cc3 and cc4 of 608 are empty - both of them are `UNKNOWN CC` label).
**Solution:** save the native track once added and use it in the selection 
(Selecting by index is not reliable because it's possible there are native tracks from previous playbacks)
Solves FEC-10819
> fix(FEC-10819): selecting 708 captions selects wrong native text track

- src/hls-adapter.js
Issue: text track doesn't have a config for styling, there is only an API for styling.
Solution: create a text container for the text track and add the options for styling the text track.
> feat(FEC-10766): create text config section and option for styling

- src/hls-adapter.js
move startTime to the sources config so it will take place only on the a specific source.
> feat(FEC-10686): move startTime config from playback to sources

- CHANGELOG.md
- package.json
- src/hls-adapter.js
If a live manifest is refreshed more than a preconfigured amount of times without any new segment,  raise a critical error and stop playback.
> feat(FEC-10657): add max stale level reloads config

- package.json
- src/hls-adapter.js
- yarn.lock
The check for `isLive()` in `addBindings` is too early - no frags are loaded in that point, so `isLive()` always returns `false`.
> fix(FEC-10657): move isLive check for LEVEL_LOADED event

- src/hls-adapter.js
Support `withCredentials` on updated request.
> feat(FEC-11091): add support for XMLHttpRequest.withCredentials in request filter 

- src/hls-adapter.js
Issue: ABR disable doesn't select on the first.
Solution: change the internal state of HLS.JS to disable the auto selection.
> fix(FEC-11126): if set abr.enabled=false, auto mode still remains enabled - HLS

- src/hls-adapter.js
Issue: native captions don't change to disable in change media.
Solution: always disable native text tracks on change media.
> fix(FEC-10832): captions not shown in change media from media with 608 captions

- src/hls-adapter.js
**the issue:**
When starting video with captions "off" and then switching to the default captions -> it takes ~10 sec to load.
similar issue was found here- FEC-11585 and was fixed, however still not solving our issue- the only difference is that in FEC-11585 the vtt file is downloaded in one file, while in our case, vtt are coming in separated fragments.
**solution:**
using hlsjs event "SUBTITLE_FRAG_PROCESSED" instead of "SUBTITLE_TRACK_LOADED".
solves FEC-11800
> fix(FEC-11800): captions taking longer to load

- src/hls-adapter.js
pass `streaming.lowLatencyMode` to hlsjs
Solves FEC-10548
Related to https://github.com/kaltura/playkit-js/pull/631
> feat(FEC-10548): Low-Latency support

- package.json
- yarn.lock
upgrade HLS.JS player to v1.2.0
solves:  FEC-12460
related pr: https://github.com/kaltura/kaltura-player-js/pull/560
> fix(FEC-12460): upgrade HLS.JS player to v1.2.0

- src/hls-adapter.js
In some cases hls.js triggers our event handlers (specifically _onAudioTrackSwitched) before the _onManifestLoaded handler. When _onAudioTracksSwitched calls _playerTracks.find, which is undefined, it crashes. 
The solution is to initialize _playerTracks with an empty array before _onManifestLoaded fills it with the real values.
> fix(FEC-12527): turning on hls debug mode in config causes the player to crash

- package.json
- test/src/hls-adapter.spec.js
- test/src/json/hls_sources.json
- yarn.lock
Upgrade hls.js to v1.2.3
related pr: https://github.com/kaltura/kaltura-player-js/pull/568
solves: FEC-12492
> feat(FEC-12492): upgrade hls.js v1.2.3

- package.json
- yarn.lock
Upgrade hls.js to v1.2.4
solves: FEC-12626
> feat(FEC-12626): upgrade hls.js to v1.2.4

- src/hls-adapter.js
fix prevents recover retry logic to run forever in hls.js for codec errors
FEC-13010
> fix(FEC-13010): exclude Hlsjs.ErrorDetails.MANIFEST_INCOMPATIBLE_CODECS_ERROR 

- .babelrc
- package.json
- test/src/hls-adapter.spec.js
- yarn.lock
Upgrade hls.js to 1.4.11
Related PR: https://github.com/kaltura/kaltura-player-js/pull/649
Resolves FEC-13212
Resolves [FEC-13322](https://kaltura.atlassian.net/browse/FEC-13322)
[FEC-13322]: https://kaltura.atlassian.net/browse/FEC-13322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13212): upgrade hls.js to 1.4.11

- src/hls-adapter.js
> fix(SUP-39117): handle when audio tracks are returned with video tracks

- src/default-config.json
**Issue**:
Console logs show the message "[Error] Category: 0 | Code: 0 | {name: internalException}" and in some cases also "ReferenceError: e is not defined"
**Explanation**:
hls.js uses a worker thread when decoding video messages
if the worker thread encounters an error, it will fallback to decoding on the main thread and will show the message "warn] > Error in "main" Web Worker, fallback to inline" (visible when playback.options.html5.hls.debug = true)
One of the changes included in the last hls.js version upgrade seems to have been a change in the worker-related code (possibly [this one](https://github.com/video-dev/hls.js/pull/5270))
The hls.js version with these changes works fine when running the player locally, where webpack-dev-server runs with "--mode development"
However, once …
> fix(SUP-39292): V7 Player v3.15.2 Shows ReferenceError

- src/default-config.json
**the issue:**
hls worker is not working.
**solution:**
remove configuration that disabled the worker.
**related PR:** https://github.com/kaltura/kaltura-player-js/pull/776
> fix(FEC-13878): enable hls worker

- src/hls-adapter.ts
**Issue:**
When play the video with caption disabled, caption is not shown after enable the caption (when the caption is default)
**Fix:**
Listen to SUBTITLE_FRAG_PROCESSED (hls event) that's triggered after the captions request and parsing then hide the captions from our side.
[SUP-42730]: https://kaltura.atlassian.net/browse/SUP-42730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-42730): Captions not showing after enabling

- src/hls-adapter.ts
**Issue:**
When playing video with cc disabled, captions are not displayed after enable the caption. this happens when we have default caption and we generate webVTT captions.
This was fixed here - [#219](https://github.com/kaltura/playkit-js-hls/pull/219) but seems it was only partial fix and was tested only when "Auto generate WebVTT captions" is enabled. 
the fix here  - [#221](https://github.com/kaltura/playkit-js-hls/pull/221) should complete the fix but was tested only on original webVTT (and also not default caption) and not in generate webVTT.
This fix is tested and working for all cases - srt, webVTT and generate webVTT not and default captions
**Fix:**
Only if there is a default caption we will listen to SUBTITLE_FRAG_PROCESSED otherwise we can hide the caption immediately …
> fix(SUP-46270): [MultiCustomer] Captions Not Showing After Enabling Them

- src/hls-adapter.ts
**Issue:**
When get parsing error with No media found, the video stops and a black screen is appear.
**Fix:**
Mimic the behavior in V2 player, stop the video and not show a black screen.
[solved ] (https://kaltura.atlassian.net/browse/SUP-45743)
> fix (SUP-45743): Errors on playback for mulitstream

- src/hls-adapter.ts
- webpack.config.js
- yarn.lock
enhancement.
**Requirement:**
The requirement is to expose `kind` field for audio and text tracks according to accessibility parameters.
- audio tracks: possible values: `main`, `description` 
- text tracks: possible values: `subtitles`, `captions`
**Changes in this PR:**
for audio tracks:
- add `kind` field to `audioTracks` parsed in hls-adapter according to `hlsAudioTrack.characteristics` field
for text tracks:
- add a function to determine whether the text track is `captions` or `subtitles` according to `track.characteristics` (same implementation as in hlsjs)
- add `kind` field to `textTracks` in hls-adapter 
also fix the playkit-js dep in webpack file.
**depends on** [PR](https://github.com/kaltura/playkit-js/pull/815)
> feat(FEC-14419): Expose Accessibility Audio \ Text Track Indications

- src/default-config.json
Add "stretchShortVideoTrack" configuration for cases where the audio is longer than the video so playback get stuck
[SUP-47527]: https://kaltura.atlassian.net/browse/SUP-47527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-47527): [Regents of Minnesota] Video Playback Issue in V7 Players
